DVDLibrary/DVDLibrary.WebUI/ViewModels/FriendVM.cs
using DVDLibrary.Models;
using DVDLibrary.Models.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace DVDLibrary.WebUI.ViewModels
{
    public class FriendVM
    {
        public List<Friend> Friend { get; set; }
        
    }
}

DVDLibrary/DVDLibrary.WebUI/ViewModels/MovieVM.cs
using DVDLibrary.Models;
using DVDLibrary.Models.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace DVDLibrary.WebUI.ViewModels
{
    public class MovieVM
    {
        //public Movie DVD { get; set; }
        public List<Movie> Movie { get; set; }
        
        public Movie SelectedMovie { get; set; }
        
        public Movie SaveMovie { get; set; }
        
       
    }
}

DVDLibrary/DVDLibrary.WebUI/Controllers/HomeController.cs
using DVDLibrary.BLL;
using DVDLibrary.Data;
using DVDLibrary.Models;
using DVDLibrary.Models.Interfaces;
using DVDLibrary.WebUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DVDLibrary.WebUI.Controllers
{
    public class HomeController : Controller
    {
        MovieManager manager = MovieManagerFactory.Create();

        // GET: Home
        public ActionResult Index()
        {
            MovieVM vm = new MovieVM();
            vm.Movie = manager.MovieList();
            return View(vm);
          
        }
    }
}

DVDLibrary/DVDLibrary.WebUI/Controllers/MovieController.cs
using DVDLibrary.BLL;
using DVDLibrary.Models;
using DVDLibrary.Models.Interfaces;
using DVDLibrary.WebUI.ViewModels;
using DVDLibrary.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DVDLibrary.WebUI.Controllers
{
    public class MovieController : Controller
    {
        MovieManager manager = MovieManagerFactory.Create();
        // GET: Movie
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ManageDVD()
        {
            MovieVM vm = new MovieVM();
            vm.Movie = manager.MovieList();
            return View(vm);
        }
        [HttpPost]
        public ActionResult ManageDVD(string title)
        {
            return View();
        }

        [HttpGet]
        public ActionResult EditDVD(string id)
        {
            List<Movie> d = manager.MovieList();
            var mToEdit = d.FirstOrDefault(m => m.Title == id);
            return View(mToEdit);

        }
        [HttpPost]
        public ActionResult EditDVD(Movie m)
        {
            List<Movie> d = manager.MovieList();
            manager.SaveMovie(m);
            return RedirectToAction("ManageDVD");
        }

        [HttpGet]
        public ActionResult AddDVD()
        {
            return View();

        }
        [HttpPost]
        public ActionResult AddDVD(Movie m)
        {
            List<Movie> d = manager.MovieList();
            manager.SaveMovie(m);
            return RedirectToAction("ManageDVD");
        }

        [HttpGet]
        public ActionResult DeleteDVD(string id)
        {
            List<Movie> d = manager.MovieList();
            var mToDelete = d.FirstOrDefault(m => m.Title == id);
            return View(mToDelete);
        }
        [HttpPost]
        public ActionResult DeleteDVD(Movie model)
        {
            manager.DeleteMovie(model);
            return RedirectToAction("ManageDVD");
        }

        [HttpGet]
        public ActionResult Friend()
        {
            FriendVM vm = new FriendVM();
            vm.Friend = manager.FriendList();
            return View(vm);

        }
        [HttpPost]
        public ActionResult Friend(string b)
        {
            
            return View();
        }


    }
}

DVDLibrary/DVDLibrary.WebUI/Views/Home/Index.cshtml
@model DVDLibrary.WebUI.ViewModels.MovieVM
@{
    ViewBag.Title = "Index";
}



<div class="row">
    <div class="col-xs-12">
        <div class="row">
            <div class="col-xs-12 col-md-3">
                <img src="http://stories.barkpost.com/wp-content/uploads/2014/04/51hmU-R8sSL._SY300_.jpg" alt="dog" style="width:200px" />
            </div>
            <div class="col-xs-12 col-md-4">
                <h2>Louie's Top Picks</h2>
               
            </div>
            <div class="col-xs-12 col-md-5,.mainImage">
                <img src="http://www.clipartkid.com/images/160/movie-reel-templates-clipart-cliparthut-free-clipart-UY6uCv-clipart.jpg" alt="Reel" style="width:400px" />
            </div>

        </div>
    </div>
</div>
<div id="owner-collection">
    <div class="row">
        <div class="col-xs-12">
            <div class="col-md-4">
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="Title"></>Search by Title</label>
                    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Title" />
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <table id="myTable" class="table table-striped" style="width: auto;">
                <thead>
                    <tr>
                        <th>Movie Title</th>
                        <th>Director</th>
                        <th>Rating</th>
                        <th>Louie's Rating</th>
                        <th>Louie's Thoughts</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var movie in Model.Movie)
                    {
                        <tr>
                            <td>@movie.Title</td>
                            <td>@movie.DirectorsName</td>
                            <td>@movie.MPAARating</td>
                            <td>@movie.UserRating bones</td>
                            <td>@movie.UserNotes</td>

                            @*-- Button trigger modal -->*@
                            <td>
                                <button type="button" class="btn btn-primary btn-sm  dvdbutton"
                                        data-toggle="modal"
                                        data-target="#myModal"
                                        data-title="@movie.Title"
                                        data-studio="@movie.Studio"
                                        data-directors="@movie.DirectorsName"
                                        data-userrating="@movie.UserRating"
                                        data-mpaarating="@movie.MPAARating"
                                        data-releasedate="@movie.ReleaseDate.ToShortDateString()"
                                        data-actors="@movie.Actors"
                                        data-usernotes="@movie.UserNotes"
                                        data-friend="@movie.Borrower"
                                        data-lentdate="@movie.LentDate.ToShortDateString()"
                                        data-returndate="@movie.ReturnDate.ToShortDateString()">

                                    Movie Details
                                </button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal -->
<div id="modal">
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Movie Details</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" class="form-control" id="DvdTitle" name="Title" readonly />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group">
                                <label>Studio</label>
                                <input type="text" class="form-control" id="DvdStudio" name="Studio" readonly/>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group">
                                <label>Director</label>
                                <input type="text" class="form-control" id="DvdDirectorsName" name="Directors" readonly/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-md-3">
                            <div class="form-group">
                                <label>Louie's Rating</label>
                                <input type="text" class="form-control" id="DvdUserRating" name="LouieRating" readonly />
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-3">
                            <div class="form-group">
                                <label>MPAA Rating</label>
                                <input type="text" class="form-control" id="DvdMPAA" name="MPAARating" readonly/>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-3">
                            <div class="form-group">
                                <label>Release Date</label>
                                <input type="text" class="form-control" id="DvdRelease" name="ReleaseDate"readonly />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-md-12">
                            <div class="form-group">
                                <label>Actors</label>
                                <input type="text" style="max-width:500px;"class="form-control" id="DvdActors" name="actors" readonly/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label>Louie's Thoughts</label>
                                <input type="text" style="max-width:500px;" class="form-control" id="DvdUserNotes" name="thoughts" readonly/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group">
                                <label>Trusted Friend</label>
                                <input type="text" class="form-control" id="DvdFriend" name="friend" readonly/>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-3">
                            <div class="form-group">
                                <label>Lent</label>
                                <input type="text" class="form-control" id="DvdLentDate" name="dateLent" readonly/>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-3">
                            <div class="form-group">
                                <label>Returned</label>
                                <input type="text" class="form-control" id="DvdReturnDate" name="dateReturned" readonly/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


@section BodyScript{
    <script src="~/Scripts/DVDScript.js"></script>
}

DVDLibrary/DVDLibrary.WebUI/Views/Movie/AddDVD.cshtml
@model DVDLibrary.Models.Movie
@{
    ViewBag.Title = "AddDVD";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        <h2>AddDVD</h2>
        @Html.ActionLink("Movie List", "Index", "Home")
    </div>

    <div class="col-xs-12 col-sm-9">
        @using (Html.BeginForm())
        {
            <div class="row">
                <h2>Movie Details</h2>
            </div>
            <div class="form-group">
                <label>Movie Title</label>
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Studio</label>
                @Html.TextBoxFor(m => m.Studio, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Director</label>
                @Html.TextBoxFor(m => m.DirectorsName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Louie's Ratings (1-10)</label>
                @Html.TextBoxFor(m => m.UserRating, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>MPAA Rating</label>
                @Html.EnumDropDownListFor(m => m.MPAARating, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Release Date</label>
                @Html.TextBoxFor(m => m.ReleaseDate, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Actors</label>
                @Html.TextBoxFor(m => m.Actors, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Louie's Thoughts</label>
                @Html.TextAreaFor(m => m.UserNotes, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Save</button>
            @Html.ActionLink("Cancel", "ManageDVD", "Movie", null, new { @class = "btn btn-sm btn-info" })
        
        }
    </div>

</div>

DVDLibrary/DVDLibrary.WebUI/Views/Movie/DeleteDVD.cshtml
@model DVDLibrary.Models.Movie
@{
    ViewBag.Title = "DeleteDVD";
}

<div class="row">
    <div class="col-xs-12">
        <h2>Delete DVD</h2>
        @Html.ActionLink("Movie List", "Index", "Home")
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(m => m.MovieId)
            @Html.HiddenFor(m => m.Title)
            <p>Are you sure you want to remove @Html.DisplayFor(m => m.Title) from your collection?</p>
            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            @Html.ActionLink("Cancel", "ManageDVD", "Movie", null, new { @class = "btn btn-sm btn-info" })
        }
    </div>
</div>

DVDLibrary/DVDLibrary.WebUI/Views/Movie/EditDVD.cshtml
@model DVDLibrary.Models.Movie
@{
    ViewBag.Title = "EditDVD";
}
<div class="row">
    <div class="col-xs-12 col-sm-3">
        <h2>Edit DVD</h2>
        @Html.ActionLink("Movie List", "Index", "Home")
    </div>

    <div class="col-xs-12 col-sm-9">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(m => m.MovieId)
            //@Html.HiddenFor(m => m.BorrowerId)

                <div class="page-header">
                    <h2>Edit Movie</h2>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label>Movie Title</label>
                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Studio</label>
                        @Html.TextBoxFor(m => m.Studio, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Director</label>
                        @Html.TextBoxFor(m => m.DirectorsName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Louie's Rating (1-10)</label>
                        @Html.TextBoxFor(m => m.UserRating, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>MPAA Rating</label>
                        @Html.EnumDropDownListFor(m => m.MPAARating, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Release Date</label>
                        @Html.TextBoxFor(m => m.ReleaseDate, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Actors</label>
                        @Html.TextAreaFor(m => m.Actors, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Louie's Thoughts</label>
                        @Html.TextAreaFor(m => m.UserNotes, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Trusted Friend</label>
                        @Html.TextBoxFor(m => m.Borrower.Borrower, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Lent</label>
                        @Html.TextBoxFor(m => m.LentDate, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Returned</label>
                        @Html.TextBoxFor(m => m.ReturnDate, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-sm btn-primary">Save</button>
                    @Html.ActionLink("Cancel", "ManageDVD", "Movie", null, new { @class = "btn btn-sm btn-info" })
                </div>
        }
    </div>
</div>

DVDLibrary/DVDLibrary.WebUI/Views/Movie/Friend.cshtml
@model DVDLibrary.WebUI.ViewModels.FriendVM
@{
    ViewBag.Title = "Friend";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        <h2>Trusted Friends</h2>
        @Html.ActionLink("Movie List", "Index", "Home")
    </div>
  
        <div class="col-xs-12 col-sm-9">
            <br/>
            
            <table id="myTable" class="table table-striped" style="width: auto;">
                <thead>
                    <tr>
                        <th>Friend's Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Friend)
                    {
                        <tr>
                            <td>@item.Borrower</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>


    </div>

DVDLibrary/DVDLibrary.WebUI/Views/Movie/ManageDVD.cshtml
@model DVDLibrary.WebUI.ViewModels.MovieVM
@{
    ViewBag.Title = "ManageDVD";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        <h2>ManageDVD</h2>
        <p>@Html.ActionLink("Add a DVD", "AddDVD", "Movie", null, new { @class = "btn btn-primary" })</p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
       
            <table class="table table-striped" style="width: auto">
                <thead>
                    <tr>
                        <th>Movie Title</th>
                        <th>Manage</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var movie in Model.Movie)
                {
                        <tr>
                            <td>@movie.Title</td>
                            <td>
                                @Html.ActionLink("Edit", "EditDVD", "Movie", new { id = movie.Title }, null) |
                                @Html.ActionLink("Delete", "DeleteDVD", "Movie", new { id = movie.Title }, null)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            
    </div>
</div>

DVDLibrary/DVDLibrary.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Louie's Picks</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Louie's Picks", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage Collection<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Manage DVD", "ManageDVD", "Movie")</li>
                            <li>@Html.ActionLink("Friend", "Friend", "Movie")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - DogOn good flicks.</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("BodyScript", false)
</body>
</html>